### ISSUE TITLE
2020-11-19 TODO-LIST

### ISSUE THREAD

**Issue by GEUP** [GEUP/EmbededProgramming_LoopStation#1]
- [ ] 학교 라즈베리파이에 깃 허브 연결

1. 라즈베리파이에 RSA Key 만들기 : 
	ssh-keygen -t rsa -C "github가입 메일 주소"
2. 생성된 키 파일인 id_rsa.pub 파일을 찾아서 텍스트로 내용복사
3. github - settings - ...KEY
4. 원격 저장소 설정 : git remote add 저장소이름 저장소SSH주소
5. 업스트림 생성: git push --set-upstream 저장소이름 master
	ssh Key 생성 시 만든 비밀번호
6. 노트북에서 github로 올리고자 하는 파일 커밋
	git add 파일명
	git commit
10. 커밋 올리기 : git push
- [ ] 안드로이드 - 라즈베리파이 MQTT 시연
- [ ] 디바이스 드라이버를 리포지토리에 추가
- [ ] 디바이스 드라이버 파일을 파이썬으로 open해보기
